name: Deploy React App from Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Fix Directory Permissions
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/test2.demo/test2.demo || true

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies and Build React App
        run: |
          npm install
          npm run build

      - name: Deploy to Apache Web Root
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/

      - name: Restart Apache
        run: |
          sudo systemctl restart apache2
